// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NFine.Data;

namespace NFine.Data
{
    [DbContext(typeof(NFineDbContext))]
    [Migration("20200927164732_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NFine.Domain.Entity.SystemManage.AreaEntity", b =>
                {
                    b.Property<string>("F_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime?>("F_CreatorTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_CreatorUserName")
                        .HasColumnType("text");

                    b.Property<bool?>("F_DeleteMark")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_DeleteTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_DeleteUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_DeleteUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_Description")
                        .HasColumnType("text");

                    b.Property<string>("F_EnCode")
                        .HasColumnType("text");

                    b.Property<bool?>("F_EnabledMark")
                        .HasColumnType("bit");

                    b.Property<string>("F_FullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("F_LastModifyTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_LastModifyUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_LastModifyUserName")
                        .HasColumnType("text");

                    b.Property<int?>("F_Layers")
                        .HasColumnType("int");

                    b.Property<string>("F_ParentId")
                        .HasColumnType("text");

                    b.Property<string>("F_SimpleSpelling")
                        .HasColumnType("text");

                    b.Property<int?>("F_SortCode")
                        .HasColumnType("int");

                    b.HasKey("F_Id");

                    b.ToTable("Sys_Area");
                });

            modelBuilder.Entity("NFine.Domain.Entity.SystemManage.ItemsDetailEntity", b =>
                {
                    b.Property<string>("F_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime?>("F_CreatorTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_CreatorUserName")
                        .HasColumnType("text");

                    b.Property<bool?>("F_DeleteMark")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_DeleteTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_DeleteUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_DeleteUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_Description")
                        .HasColumnType("text");

                    b.Property<bool?>("F_EnabledMark")
                        .HasColumnType("bit");

                    b.Property<bool?>("F_IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("F_ItemCode")
                        .HasColumnType("text");

                    b.Property<string>("F_ItemId")
                        .HasColumnType("text");

                    b.Property<string>("F_ItemName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("F_LastModifyTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_LastModifyUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_LastModifyUserName")
                        .HasColumnType("text");

                    b.Property<int?>("F_Layers")
                        .HasColumnType("int");

                    b.Property<string>("F_ParentId")
                        .HasColumnType("text");

                    b.Property<string>("F_SimpleSpelling")
                        .HasColumnType("text");

                    b.Property<int?>("F_SortCode")
                        .HasColumnType("int");

                    b.HasKey("F_Id");

                    b.ToTable("Sys_ItemsDetail");
                });

            modelBuilder.Entity("NFine.Domain.Entity.SystemManage.ItemsEntity", b =>
                {
                    b.Property<string>("F_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime?>("F_CreatorTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_CreatorUserName")
                        .HasColumnType("text");

                    b.Property<bool?>("F_DeleteMark")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_DeleteTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_DeleteUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_DeleteUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_Description")
                        .HasColumnType("text");

                    b.Property<string>("F_EnCode")
                        .HasColumnType("text");

                    b.Property<bool?>("F_EnabledMark")
                        .HasColumnType("bit");

                    b.Property<string>("F_FullName")
                        .HasColumnType("text");

                    b.Property<bool?>("F_IsTree")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_LastModifyTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_LastModifyUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_LastModifyUserName")
                        .HasColumnType("text");

                    b.Property<int?>("F_Layers")
                        .HasColumnType("int");

                    b.Property<string>("F_ParentId")
                        .HasColumnType("text");

                    b.Property<int?>("F_SortCode")
                        .HasColumnType("int");

                    b.HasKey("F_Id");

                    b.ToTable("Sys_Items");
                });

            modelBuilder.Entity("NFine.Domain.Entity.SystemManage.ModuleButtonEntity", b =>
                {
                    b.Property<string>("F_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<bool?>("F_AllowDelete")
                        .HasColumnType("bit");

                    b.Property<bool?>("F_AllowEdit")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_CreatorTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_CreatorUserName")
                        .HasColumnType("text");

                    b.Property<bool?>("F_DeleteMark")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_DeleteTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_DeleteUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_DeleteUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_Description")
                        .HasColumnType("text");

                    b.Property<string>("F_EnCode")
                        .HasColumnType("text");

                    b.Property<bool?>("F_EnabledMark")
                        .HasColumnType("bit");

                    b.Property<string>("F_FullName")
                        .HasColumnType("text");

                    b.Property<string>("F_Icon")
                        .HasColumnType("text");

                    b.Property<bool?>("F_IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("F_JsEvent")
                        .HasColumnType("text");

                    b.Property<DateTime?>("F_LastModifyTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_LastModifyUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_LastModifyUserName")
                        .HasColumnType("text");

                    b.Property<int?>("F_Layers")
                        .HasColumnType("int");

                    b.Property<int?>("F_Location")
                        .HasColumnType("int");

                    b.Property<string>("F_ModuleId")
                        .HasColumnType("text");

                    b.Property<string>("F_ParentId")
                        .HasColumnType("text");

                    b.Property<int?>("F_SortCode")
                        .HasColumnType("int");

                    b.Property<bool?>("F_Split")
                        .HasColumnType("bit");

                    b.Property<string>("F_UrlAddress")
                        .HasColumnType("text");

                    b.HasKey("F_Id");

                    b.ToTable("Sys_ModuleButton");
                });

            modelBuilder.Entity("NFine.Domain.Entity.SystemManage.ModuleEntity", b =>
                {
                    b.Property<string>("F_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<bool?>("F_AllowDelete")
                        .HasColumnType("bit");

                    b.Property<bool?>("F_AllowEdit")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_CreatorTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_CreatorUserName")
                        .HasColumnType("text");

                    b.Property<bool?>("F_DeleteMark")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_DeleteTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_DeleteUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_DeleteUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_Description")
                        .HasColumnType("text");

                    b.Property<string>("F_EnCode")
                        .HasColumnType("text");

                    b.Property<bool?>("F_EnabledMark")
                        .HasColumnType("bit");

                    b.Property<string>("F_FullName")
                        .HasColumnType("text");

                    b.Property<string>("F_Icon")
                        .HasColumnType("text");

                    b.Property<bool?>("F_IsExpand")
                        .HasColumnType("bit");

                    b.Property<bool?>("F_IsMenu")
                        .HasColumnType("bit");

                    b.Property<bool?>("F_IsPublic")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_LastModifyTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_LastModifyUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_LastModifyUserName")
                        .HasColumnType("text");

                    b.Property<int?>("F_Layers")
                        .HasColumnType("int");

                    b.Property<string>("F_ParentId")
                        .HasColumnType("text");

                    b.Property<int?>("F_SortCode")
                        .HasColumnType("int");

                    b.Property<string>("F_Target")
                        .HasColumnType("text");

                    b.Property<string>("F_UrlAddress")
                        .HasColumnType("text");

                    b.HasKey("F_Id");

                    b.ToTable("Sys_Module");
                });

            modelBuilder.Entity("NFine.Domain.Entity.SystemManage.NewsInfoEntity", b =>
                {
                    b.Property<string>("F_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("F_Content")
                        .HasColumnType("text");

                    b.Property<DateTime?>("F_CreatorTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_CreatorUserName")
                        .HasColumnType("text");

                    b.Property<bool?>("F_DeleteMark")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_DeleteTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_DeleteUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_DeleteUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("F_LastModifyTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_LastModifyUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_LastModifyUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_Spokesman")
                        .HasColumnType("text");

                    b.Property<bool>("F_Status")
                        .HasColumnType("bit");

                    b.Property<string>("F_Title")
                        .HasColumnType("text");

                    b.Property<int>("F_Type")
                        .HasColumnType("int");

                    b.HasKey("F_Id");

                    b.ToTable("Sys_NewsInfo");
                });

            modelBuilder.Entity("NFine.Domain.Entity.SystemManage.OrganizeEntity", b =>
                {
                    b.Property<string>("F_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("F_Address")
                        .HasColumnType("text");

                    b.Property<bool?>("F_AllowDelete")
                        .HasColumnType("bit");

                    b.Property<bool?>("F_AllowEdit")
                        .HasColumnType("bit");

                    b.Property<string>("F_AreaId")
                        .HasColumnType("text");

                    b.Property<string>("F_CategoryId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("F_CreatorTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_CreatorUserName")
                        .HasColumnType("text");

                    b.Property<bool?>("F_DeleteMark")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_DeleteTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_DeleteUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_DeleteUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_Description")
                        .HasColumnType("text");

                    b.Property<string>("F_Email")
                        .HasColumnType("text");

                    b.Property<string>("F_EnCode")
                        .HasColumnType("text");

                    b.Property<bool?>("F_EnabledMark")
                        .HasColumnType("bit");

                    b.Property<string>("F_Fax")
                        .HasColumnType("text");

                    b.Property<string>("F_FullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("F_LastModifyTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_LastModifyUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_LastModifyUserName")
                        .HasColumnType("text");

                    b.Property<int?>("F_Layers")
                        .HasColumnType("int");

                    b.Property<string>("F_ManagerId")
                        .HasColumnType("text");

                    b.Property<string>("F_MobilePhone")
                        .HasColumnType("text");

                    b.Property<string>("F_ParentId")
                        .HasColumnType("text");

                    b.Property<string>("F_ShortName")
                        .HasColumnType("text");

                    b.Property<int?>("F_SortCode")
                        .HasColumnType("int");

                    b.Property<string>("F_TelePhone")
                        .HasColumnType("text");

                    b.Property<string>("F_WeChat")
                        .HasColumnType("text");

                    b.HasKey("F_Id");

                    b.ToTable("Sys_Organize");
                });

            modelBuilder.Entity("NFine.Domain.Entity.SystemManage.RoleAuthorizeEntity", b =>
                {
                    b.Property<string>("F_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime?>("F_CreatorTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_CreatorUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_DeleteUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_ItemId")
                        .HasColumnType("text");

                    b.Property<int?>("F_ItemType")
                        .HasColumnType("int");

                    b.Property<string>("F_LastModifyUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_ObjectId")
                        .HasColumnType("text");

                    b.Property<int?>("F_ObjectType")
                        .HasColumnType("int");

                    b.Property<int?>("F_SortCode")
                        .HasColumnType("int");

                    b.HasKey("F_Id");

                    b.ToTable("Sys_RoleAuthorize");
                });

            modelBuilder.Entity("NFine.Domain.Entity.SystemManage.RoleEntity", b =>
                {
                    b.Property<string>("F_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<bool?>("F_AllowDelete")
                        .HasColumnType("bit");

                    b.Property<bool?>("F_AllowEdit")
                        .HasColumnType("bit");

                    b.Property<int?>("F_Category")
                        .HasColumnType("int");

                    b.Property<DateTime?>("F_CreatorTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_CreatorUserName")
                        .HasColumnType("text");

                    b.Property<bool?>("F_DeleteMark")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_DeleteTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_DeleteUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_DeleteUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_Description")
                        .HasColumnType("text");

                    b.Property<string>("F_EnCode")
                        .HasColumnType("text");

                    b.Property<bool?>("F_EnabledMark")
                        .HasColumnType("bit");

                    b.Property<string>("F_FullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("F_LastModifyTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_LastModifyUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_LastModifyUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_OrganizeId")
                        .HasColumnType("text");

                    b.Property<int?>("F_SortCode")
                        .HasColumnType("int");

                    b.Property<string>("F_Type")
                        .HasColumnType("text");

                    b.HasKey("F_Id");

                    b.ToTable("Sys_Role");
                });

            modelBuilder.Entity("NFine.Domain.Entity.SystemManage.UserEntity", b =>
                {
                    b.Property<string>("F_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("F_Account")
                        .HasColumnType("text");

                    b.Property<DateTime?>("F_Birthday")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("F_CreatorTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_CreatorUserName")
                        .HasColumnType("text");

                    b.Property<bool?>("F_DeleteMark")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_DeleteTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_DeleteUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_DeleteUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_DepartmentId")
                        .HasColumnType("text");

                    b.Property<string>("F_Description")
                        .HasColumnType("text");

                    b.Property<string>("F_DutyId")
                        .HasColumnType("text");

                    b.Property<string>("F_Email")
                        .HasColumnType("text");

                    b.Property<bool?>("F_EnabledMark")
                        .HasColumnType("bit");

                    b.Property<bool?>("F_Gender")
                        .HasColumnType("bit");

                    b.Property<string>("F_HeadIcon")
                        .HasColumnType("text");

                    b.Property<bool?>("F_IsAdministrator")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_LastModifyTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_LastModifyUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_LastModifyUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_ManagerId")
                        .HasColumnType("text");

                    b.Property<string>("F_MobilePhone")
                        .HasColumnType("text");

                    b.Property<string>("F_NickName")
                        .HasColumnType("text");

                    b.Property<string>("F_OrganizeId")
                        .HasColumnType("text");

                    b.Property<string>("F_RealName")
                        .HasColumnType("text");

                    b.Property<string>("F_RoleId")
                        .HasColumnType("text");

                    b.Property<int?>("F_SecurityLevel")
                        .HasColumnType("int");

                    b.Property<string>("F_Signature")
                        .HasColumnType("text");

                    b.Property<int?>("F_SortCode")
                        .HasColumnType("int");

                    b.Property<string>("F_WeChat")
                        .HasColumnType("text");

                    b.HasKey("F_Id");

                    b.ToTable("Sys_User");
                });

            modelBuilder.Entity("NFine.Domain.Entity.SystemManage.UserLogOnEntity", b =>
                {
                    b.Property<string>("F_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime?>("F_AllowEndTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("F_AllowStartTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_AnswerQuestion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("F_ChangePasswordDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("F_CheckIPAddress")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_FirstVisitTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_Language")
                        .HasColumnType("text");

                    b.Property<DateTime?>("F_LastVisitTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("F_LockEndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("F_LockStartDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("F_LogOnCount")
                        .HasColumnType("int");

                    b.Property<bool?>("F_MultiUserLogin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_PreviousVisitTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_Question")
                        .HasColumnType("text");

                    b.Property<string>("F_Theme")
                        .HasColumnType("text");

                    b.Property<string>("F_UserId")
                        .HasColumnType("text");

                    b.Property<bool?>("F_UserOnLine")
                        .HasColumnType("bit");

                    b.Property<string>("F_UserPassword")
                        .HasColumnType("text");

                    b.Property<string>("F_UserSecretkey")
                        .HasColumnType("text");

                    b.HasKey("F_Id");

                    b.ToTable("Sys_UserLogOn");
                });

            modelBuilder.Entity("NFine.Domain.Entity.SystemSecurity.DbBackupEntity", b =>
                {
                    b.Property<string>("F_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime?>("F_BackupTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_BackupType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("F_CreatorTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_CreatorUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_DbName")
                        .HasColumnType("text");

                    b.Property<bool?>("F_DeleteMark")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_DeleteTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_DeleteUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_DeleteUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_Description")
                        .HasColumnType("text");

                    b.Property<bool?>("F_EnabledMark")
                        .HasColumnType("bit");

                    b.Property<string>("F_FileName")
                        .HasColumnType("text");

                    b.Property<string>("F_FilePath")
                        .HasColumnType("text");

                    b.Property<string>("F_FileSize")
                        .HasColumnType("text");

                    b.Property<DateTime?>("F_LastModifyTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_LastModifyUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_LastModifyUserName")
                        .HasColumnType("text");

                    b.Property<int?>("F_SortCode")
                        .HasColumnType("int");

                    b.HasKey("F_Id");

                    b.ToTable("Sys_DbBackup");
                });

            modelBuilder.Entity("NFine.Domain.Entity.SystemSecurity.FilterIPEntity", b =>
                {
                    b.Property<string>("F_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime?>("F_CreatorTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_CreatorUserName")
                        .HasColumnType("text");

                    b.Property<bool?>("F_DeleteMark")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("F_DeleteTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_DeleteUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_DeleteUserName")
                        .HasColumnType("text");

                    b.Property<string>("F_Description")
                        .HasColumnType("text");

                    b.Property<bool?>("F_EnabledMark")
                        .HasColumnType("bit");

                    b.Property<string>("F_EndIP")
                        .HasColumnType("text");

                    b.Property<DateTime?>("F_LastModifyTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_LastModifyUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_LastModifyUserName")
                        .HasColumnType("text");

                    b.Property<int?>("F_SortCode")
                        .HasColumnType("int");

                    b.Property<string>("F_StartIP")
                        .HasColumnType("text");

                    b.Property<bool?>("F_Type")
                        .HasColumnType("bit");

                    b.HasKey("F_Id");

                    b.ToTable("Sys_FilterIP");
                });

            modelBuilder.Entity("NFine.Domain.Entity.SystemSecurity.LogEntity", b =>
                {
                    b.Property<string>("F_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("F_Account")
                        .HasColumnType("text");

                    b.Property<DateTime?>("F_CreatorTime")
                        .HasColumnType("datetime");

                    b.Property<string>("F_CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("F_CreatorUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("F_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("F_Description")
                        .HasColumnType("text");

                    b.Property<string>("F_IPAddress")
                        .HasColumnType("text");

                    b.Property<string>("F_IPAddressName")
                        .HasColumnType("text");

                    b.Property<string>("F_ModuleId")
                        .HasColumnType("text");

                    b.Property<string>("F_ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("F_NickName")
                        .HasColumnType("text");

                    b.Property<bool?>("F_Result")
                        .HasColumnType("bit");

                    b.Property<string>("F_Type")
                        .HasColumnType("text");

                    b.HasKey("F_Id");

                    b.ToTable("Sys_Log");
                });
#pragma warning restore 612, 618
        }
    }
}
