version: '3.4'
services:
    nat:
        container_name: nat  
        image: ${DOCKER_REGISTRY-}nfineweb
        ports:
            - "6000:80"
        depends_on:
          - db
        links:
          - db
        volumes:
          - "${APP_DIR}/appsettings.Production.json:/app/appsettings.Production.json"
        networks:
          - nat-network
    db:
        container_name: db  
        image: mysql:5.7.28
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: [
            '--character-set-server=utf8',
            '--collation-server=utf8_general_ci',
            ]
        volumes:
            - "${APP_DIR}/data:/var/lib/mysql"
        networks:
            - nat-network


networks: 
  nat-network:
      driver:  bridge
