version: '3.4'

services:
  nfine.web:
    image: ${DOCKER_REGISTRY-}nfineweb
    build:
        context: .
        dockerfile: NFine.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
