version: '3.4'
services:
    nfine.web:
        container_name: nat  
        image: ${DOCKER_REGISTRY-}nfineweb
        build:
          context: .
          dockerfile: NFine.Web/Dockerfile
        depends_on:
          - db
        links:
          - db
        volumes:
          - "${APP_DIR}/appsettings.Production.json:/app/appsettings.Production.json"
        networks:
          - nat-network
    db:
        container_name: db  
        image: mysql:8.0
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASS: ${MYSQL_PASS}
        volumes:
            - "${APP_DIR}/data:/var/lib/mysql"
        networks:
            - nat-network

    pma:
        image: phpmyadmin
        container_name: pma
        restart: always
        depends_on:
            - db
        links:
            - db
        environment:
            TZ: "Asia/Shanghai"
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ABSOLUTE_URI: "http://mysqladmin/pma/"
        ports:
            - "8082:80"
        networks:
            - nat-network

networks: 
  nat-network:
      driver:  bridge
