version: '3.4'
services:
  db:
    container_name: db  
    image: mysql:5.7.28
    restart: always
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_ROOT_HOST: '%'
    command: [
        '--character-set-server=utf8',
        '--collation-server=utf8_general_ci',
        '--lower_case_table_names=1'
        ]
    volumes:
        - "${APP_DIR}/data:/var/lib/mysql"
    networks:
        - nat-network

  nat:
    container_name: nat  
    image: ${DOCKER_REGISTRY-}nfineweb
    depends_on:
        - db
    links:
        - db
    volumes:
        - "${APP_DIR}/appsettings.Production.json:/app/appsettings.Production.json"
    networks:
        - nat-network

  natapi:
    container_name: natapi  
    image: ${DOCKER_REGISTRY-}nfinemobile
    depends_on:
        - db
    links:
        - db
    volumes:
        - "${APP_DIR}/appsettings.Production.json:/app/appsettings.Production.json"
    networks:
      - nat-network

  nginx:
    restart: always
    container_name: web  
    image: nginx
    depends_on:
        - nat
        - natapi
    links:
        - nat
        - natapi
    ports:
      - 6060:80
    volumes:
      - "${APP_DIR}/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - nat-network

networks: 
  nat-network:
      driver:  bridge
